# More syntax details at: https://docs.travis-ci.com/user/customizing-the-build
# Workaround present for https://github.com/sunqm/pyscf/issues/71

sudo: false
language: python
group: deprecated-2017Q4
os: linux

git:
  depth: 3

addons:
  apt:
    packages:
    - gcc
    - g++
    - gfortran
    - libblas-dev
    - cmake

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

virtualenv:
    system_site_packages: true
    
before_install:
  - pip install --upgrade pip
  - pip install numpy scipy h5py nose nose-exclude
    
install:
  - > 
    cd pyscf/lib &&
    mkdir build &&
    cd build &&
    cmake .. &&
    make &&
    cd ../..

before_script:
  - export PYTHONPATH=$(pwd):$PYTHONPATH
  - rm $TRAVIS_BUILD_DIR/pyscf/pbc/tools/pyscf_ase.py

script:
  - >
    nosetests -v -e geomopt -e dmrgscf -e fciqmcscf -e icmpspt -e examples -e nao
    -e shci
    -e test_bz
    -e test_mc2step_4o4e
    -e test_ks_noimport
    -e test_jk_single_kpt
    -e test_jk_hermi0
    -e test_j_kpts
    -e test_k_kpts
    -e high_cost
    -e call_in_background
