{% set data = load_setup_py_data() %}


package:
  name: "pyscf"
  version: "{{ data['version'] }}"

source:
  path: ..

build:
  number: 0

requirements:
  host:
    - pip
    - python
    - numpy 1.18
    - scipy
    - h5py
  run:
    - python

test:
  imports:
    - pyscf

about:
  home: {{ data['url'] }}
  license: {{ data['license'] }}
  summary: {{ data['description'] }}
