{% set data = load_setup_py_data() %}


package:
  name: "pyscf"
  version: "{{ data['version'] }}"

source:
  path: ..

build:
  number: 0
  script: pip install numpy
          pip install . -vv
          

requirements:
  build:
    - cmake
    - make
    - mkl-devel
    - blas
    - numpy
  host:
    - pip
    - python
    - numpy
    - scipy
    - h5py
  run:
    - python
    - numpy
    - h5py
    - scipy

test:
  imports:
    - pyscf

about:
  home: {{ data['url'] }}
  license: {{ data['license'] }}
  summary: {{ data['description'] }}
