{% set data = load_setup_py_data() %}


package:
  name: "pyscf"
  version: "{{ data['version'] }}"

source:
  path: ..

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - numpy
    - scipy
    - h5py
  host:
    - pip
    - python
    - numpy
    - scipy
    - h5py
  run:
    - python

test:
  imports:
    - pyscf

about:
  home: {{ data['url'] }}
  license: {{ data['license'] }}
  summary: {{ data['description'] }}
