# https://docs.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions
#
# Contributors to the evolution of this form:
#
#  sunqm
#  fishjojo
#  mjw99
#  yangcal
#  maxscheurer
#
name: CI

on: [push, pull_request]

jobs:
  linux:

    runs-on: ubuntu-18.04

    strategy:
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Resolve system dependencies
        run: sudo ./.github/workflows/ci_ubuntu/deps_apt.sh 
      - name: Resolve python dependencies
        run: ./.github/workflows/ci_ubuntu/python_deps.sh
      - name: Build PySCF
        run: ./.github/workflows/ci_ubuntu/build_pyscf.sh
      - name: Test
        working-directory: ./pyscf
        run: ../.github/workflows/ci_ubuntu/run_tests.sh
      - name: Upload to codecov
        uses: codecov/codecov-action@v1.0.13
        with:
          token: ${{secrets.CODECOV_TOKEN}}
