name: Build and Publish Conda Package


on: [push, pull_request]

jobs:
  publish:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Install deps
        run: ./.github/workflows/ci_linux/deps_apt.sh
    - name: Install python deps
        run: ./.github/workflows/ci_linux/python_deps.sh
    - name: publish-to-conda
      uses: fcakyon/conda-publish-action@v1.3
      with:
        subdir: 'conda'
        anacondatoken: ${{ secrets.ANACONDA_TOKEN }}
        platforms: 'linux'
